services:
  backend:
    volumes:
      - ./backend/src/:/backend/src/:Z
      - ./backend/run.py:/backend/run.py:Z
      - ./backend/migrations/:/backend/migrations:Z
      - ./backend/alembic.ini:/backend/alembic.ini:Z
    build:
      target: development
    environment:
      - DEV_MODE=true
    ports:
      - "8000:8000"

  frontend:
    volumes:
      - ./frontend/app/:/frontend/app/:Z
      - /frontend/app/node_modules
      - /frontend/app/.react-router
    ports:
      - "5173:5173"
    build:
      target: development

  mail-server:
    ports:
      - "8025:8025"
      - "1025:1025"

  object-storage:
    ports:
      - "9900:9000"
      - "9901:9001"

  relational-db:
    ports:
      - "5400:5432"
