services:
  ai-firewall:
    restart: unless-stopped
    image: ghcr.io/techarohq/anubis:latest
    environment:
      - BIND=:5000
      - DIFFICULTY=5
      - SERVE_ROBOTS_TXT=true
      - TARGET=http://frontend:5173
      - OG_PASSTHROUGH=true
      - OG_EXPIRY_TIME=24h
    depends_on:
      frontend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 1s

  reverse-proxy: # TODO: many logs for some reason
    image: caddy:alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      ai-firewall:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-t", "1", "--spider", "--no-verbose", "http://localhost:8000" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 2s
    volumes:
      - caddy_config:/config
      - ./conf:/etc/caddy
      - caddy_data:/data

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      target: production
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost:5173').then(r => process.exit(r.ok ? 0 : 1))"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      target: production
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 1s
    depends_on:
      object-storage:
        condition: service_healthy
      relational-db:
        condition: service_healthy

  relational-db:
    image: postgres:17
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 2s
      retries: 5
      start_period: 5s
      timeout: 3s

  object-storage:
    image: minio/minio
    restart: always
    env_file:
      - .env
    volumes:
      - minio_data:/data
    command: ["server", "--console-address", ":9001", "/data"]
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 2s
      retries: 5
      start_period: 10s
      timeout: 3s

  mail-server:
    image: axllent/mailpit
    restart: always

volumes:
  postgres_data:
  caddy_config:
  minio_data:
  caddy_data:
