"""initial schema

Revision ID: 902ce20b63d2
Revises:
Create Date: 2026-04-13 22:25:47.505244

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import src

# revision identifiers, used by Alembic.
revision: str = "902ce20b63d2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), nullable=False),
        sa.Column("modifiedAt", sa.DateTime(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("deadline", sa.DateTime(), nullable=False),
        sa.Column("fileHash", sa.String(), nullable=True),
        sa.Column("subtasks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel"],
            ["channels.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("permissions", src.core.permissions.Permissions(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("password_hashed", sa.String(), nullable=False),
        sa.Column("initialized", sa.Boolean(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel"],
            ["channels.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    op.create_table(
        "news",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(), nullable=True),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("postedAt", sa.DateTime(), nullable=False),
        sa.Column("modifiedAt", sa.DateTime(), nullable=False),
        sa.Column("by", sa.Integer(), nullable=False),
        sa.Column("bound_task_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bound_task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["channel"],
            ["channels.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("news")
    op.drop_table("users")
    op.drop_table("tasks")
    op.drop_table("channels")
    # ### end Alembic commands ###
